-- 1. プレイヤー（とお金）
CREATE TABLE player (
    uid VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    -- 所持金：CHECK制約でDBレベルでもマイナスを防ぐ（多層防御）
    gold BIGINT NOT NULL DEFAULT 0 CHECK (gold >= 0),
    PRIMARY KEY (uid)
);

-- 2. アイテムマスタ（辞書）
CREATE TABLE item_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    price INT NOT NULL,
    PRIMARY KEY (id)
);

-- 3. プレイヤーの持ち物（インベントリ）
CREATE TABLE player_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_uid VARCHAR(255) NOT NULL,
    item_id BIGINT NOT NULL,
    -- 所持数：ここもマイナス禁止
    quantity INT NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    
    PRIMARY KEY (id),
    
    -- 外部キー制約
    CONSTRAINT fk_player_item_player FOREIGN KEY (player_uid) REFERENCES player (uid),
    CONSTRAINT fk_player_item_item FOREIGN KEY (item_id) REFERENCES item_master (id),
    
    -- ユニーク制約: 「Aさんがポーションを持つ」という行は1つだけ
    -- これにより、同じアイテムが複数行に分かれるのを防ぎ、ロックしやすくする
    CONSTRAINT uq_player_item UNIQUE (player_uid, item_id)
);